name: 'manuais-temas'

services:

  nginx:
    image: nginx:1.31-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    environment:
      # Variables for Front-end
      FRONT_SERVER_NAME_TRAY: manuais.tray.local
      FRONT_SERVER_NAME_BAGY: manuais.bagy.local
      FRONT_PORT: 5173
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      # Used to resolve the host IP for the nginx config
      - "host.docker.internal:host-gateway"
    networks:
      app:
        aliases:
          # Includes all hosts as alias so docker can resolve hosts automatically
          - manuais.tray.local
          - manuais.bagy.local
    restart: on-failure:3

networks:
  app:
    driver: bridge